/* Generated By:JavaCC: Do not edit this line. SintaxisConstants.java */
package Analizador;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SintaxisConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FN = 5;
  /** RegularExpression Id. */
  int LET = 6;
  /** RegularExpression Id. */
  int MUT = 7;
  /** RegularExpression Id. */
  int RETURN = 8;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int ELSE = 10;
  /** RegularExpression Id. */
  int TRUE = 11;
  /** RegularExpression Id. */
  int FALSE = 12;
  /** RegularExpression Id. */
  int I32 = 13;
  /** RegularExpression Id. */
  int F64 = 14;
  /** RegularExpression Id. */
  int BOOL = 15;
  /** RegularExpression Id. */
  int STR = 16;
  /** RegularExpression Id. */
  int INTKEY = 17;
  /** RegularExpression Id. */
  int STRINGKEY = 18;
  /** RegularExpression Id. */
  int PRINTLN = 19;
  /** RegularExpression Id. */
  int PLUS = 20;
  /** RegularExpression Id. */
  int MINUS = 21;
  /** RegularExpression Id. */
  int MULTIPLICATION = 22;
  /** RegularExpression Id. */
  int DIVISION = 23;
  /** RegularExpression Id. */
  int MODULUS = 24;
  /** RegularExpression Id. */
  int EQUALTO = 25;
  /** RegularExpression Id. */
  int NOTEQUAL = 26;
  /** RegularExpression Id. */
  int LESSTHAN = 27;
  /** RegularExpression Id. */
  int GREATERTHAN = 28;
  /** RegularExpression Id. */
  int LESSTHANEQUAL = 29;
  /** RegularExpression Id. */
  int GREATERTHANEQUAL = 30;
  /** RegularExpression Id. */
  int AND = 31;
  /** RegularExpression Id. */
  int OR = 32;
  /** RegularExpression Id. */
  int NOT = 33;
  /** RegularExpression Id. */
  int EQUAL = 34;
  /** RegularExpression Id. */
  int LPARENT = 35;
  /** RegularExpression Id. */
  int RPARENT = 36;
  /** RegularExpression Id. */
  int LBRACKET = 37;
  /** RegularExpression Id. */
  int RBRACKET = 38;
  /** RegularExpression Id. */
  int LBRACE = 39;
  /** RegularExpression Id. */
  int RBRACE = 40;
  /** RegularExpression Id. */
  int COMMA = 41;
  /** RegularExpression Id. */
  int PUNTOYCOMA = 42;
  /** RegularExpression Id. */
  int COLON = 43;
  /** RegularExpression Id. */
  int ARROW = 44;
  /** RegularExpression Id. */
  int INT = 45;
  /** RegularExpression Id. */
  int FLOAT = 46;
  /** RegularExpression Id. */
  int STRING = 47;
  /** RegularExpression Id. */
  int IDENTIFIER = 48;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"fn\"",
    "\"let\"",
    "\"mut\"",
    "\"return\"",
    "\"if\"",
    "\"else\"",
    "\"true\"",
    "\"false\"",
    "\"i32\"",
    "\"f64\"",
    "\"bool\"",
    "\"str\"",
    "\"int\"",
    "\"String\"",
    "\"println!\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"->\"",
    "<INT>",
    "<FLOAT>",
    "<STRING>",
    "<IDENTIFIER>",
  };

}
