/* Generated By:JavaCC: Do not edit this line. SintaxisConstants.java */
package Analizador;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SintaxisConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FN = 5;
  /** RegularExpression Id. */
  int LET = 6;
  /** RegularExpression Id. */
  int MUT = 7;
  /** RegularExpression Id. */
  int RETURN = 8;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int ELSE = 10;
  /** RegularExpression Id. */
  int ELSEIF = 11;
  /** RegularExpression Id. */
  int WHILE = 12;
  /** RegularExpression Id. */
  int FOR = 13;
  /** RegularExpression Id. */
  int IN = 14;
  /** RegularExpression Id. */
  int TRUE = 15;
  /** RegularExpression Id. */
  int FALSE = 16;
  /** RegularExpression Id. */
  int I32 = 17;
  /** RegularExpression Id. */
  int F64 = 18;
  /** RegularExpression Id. */
  int BOOL = 19;
  /** RegularExpression Id. */
  int STR = 20;
  /** RegularExpression Id. */
  int STRING_KEYWORD = 21;
  /** RegularExpression Id. */
  int PRINTLN = 22;
  /** RegularExpression Id. */
  int PRINT = 23;
  /** RegularExpression Id. */
  int PLUS = 24;
  /** RegularExpression Id. */
  int MINUS = 25;
  /** RegularExpression Id. */
  int MULTIPLICATION = 26;
  /** RegularExpression Id. */
  int DIVISION = 27;
  /** RegularExpression Id. */
  int MODULUS = 28;
  /** RegularExpression Id. */
  int EQUALTO = 29;
  /** RegularExpression Id. */
  int NOTEQUAL = 30;
  /** RegularExpression Id. */
  int LESSTHAN = 31;
  /** RegularExpression Id. */
  int GREATERTHAN = 32;
  /** RegularExpression Id. */
  int LESSTHANEQUAL = 33;
  /** RegularExpression Id. */
  int GREATERTHANEQUAL = 34;
  /** RegularExpression Id. */
  int AND = 35;
  /** RegularExpression Id. */
  int OR = 36;
  /** RegularExpression Id. */
  int NOT = 37;
  /** RegularExpression Id. */
  int EQUAL = 38;
  /** RegularExpression Id. */
  int LPARENT = 39;
  /** RegularExpression Id. */
  int RPARENT = 40;
  /** RegularExpression Id. */
  int LBRACKET = 41;
  /** RegularExpression Id. */
  int RBRACKET = 42;
  /** RegularExpression Id. */
  int LBRACE = 43;
  /** RegularExpression Id. */
  int RBRACE = 44;
  /** RegularExpression Id. */
  int COMMA = 45;
  /** RegularExpression Id. */
  int PUNTOYCOMA = 46;
  /** RegularExpression Id. */
  int COLON = 47;
  /** RegularExpression Id. */
  int ARROW = 48;
  /** RegularExpression Id. */
  int INT = 49;
  /** RegularExpression Id. */
  int FLOAT = 50;
  /** RegularExpression Id. */
  int STRING = 51;
  /** RegularExpression Id. */
  int IDENTIFIER = 52;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"fn\"",
    "\"let\"",
    "\"mut\"",
    "\"return\"",
    "\"if\"",
    "\"else\"",
    "\"else if\"",
    "\"while\"",
    "\"for\"",
    "\"in\"",
    "\"true\"",
    "\"false\"",
    "\"i32\"",
    "\"f64\"",
    "\"bool\"",
    "\"str\"",
    "\"String\"",
    "\"println!\"",
    "\"print!\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"->\"",
    "<INT>",
    "<FLOAT>",
    "<STRING>",
    "<IDENTIFIER>",
    "\"\"",
  };

}
